name: Release node images

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag for the images (e.g.: beta)'
        required: true
      apify_version:
        description: 'Apify SDK version (e.g.: ^1.0.0)'
        required: true

  repository_dispatch:
    types: [ build-images ]

env:
  RELEASE_TAG: ${{ github.event.inputs.release_tag || github.event.client_payload.release_tag }}
  APIFY_VERSION: ${{ github.event.inputs.apify_version || github.event.client_payload.apify_version }}
  NODE_LATEST: 16

jobs:
  # Build master images that are not dependent on existing builds.   
  build-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [node]
        node-version: [14, 15, 16]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Prepare image tags
        id: prepare-tags
        uses: actions/github-script@v4
        env:
          CURRENT_NODE: ${{ matrix.node-version }}
          LATEST_NODE: ${{ env.NODE_LATEST }}
          RELEASE_TAG: ${{ env.RELEASE_TAG }}
          IMAGE_NAME: apify/actor-${{ matrix.image-name }}
        with:
          result-encoding: string
          script: |
             const script = require("../.github/scripts/prepare-image-tags.js");
             return script()
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set Dependency Versions
        run: |
          cd ${{ matrix.image-name }}
          node ../.github/scripts/set-dependency-versions.js
      -
        # It seems that it takes at least two minutes before a newly published version
        # becomes available in the NPM registry. We wait before starting the image builds.
        name: Wait For Package Registry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 2 # timeout for a single attempt
          max_attempts: 3
          retry_wait_seconds: 60 # wait between retries
          command: cd ${{ matrix.image-name }} && npm i --dry-run
      -
        name: Build and tag image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image-name }}
          file: ./${{ matrix.image-name }}/Dockerfile
          build-args: NODE_VERSION=${{ matrix.node-version }}
          load: true
          tags: ${{ steps.prepare-tags.outputs.result }}
      -
        name: Test image with release tag
        if: ${{ matrix.node-version == env.NODE_LATEST }}
        run: docker run apify/actor-${{ matrix.image-name }}:${{ env.RELEASE_TAG }}
      -
        name: Test image with node version tag
        if: ${{ env.RELEASE_TAG == 'latest'}}
        run: docker run apify/actor-${{ matrix.image-name }}:${{ matrix.node-version }}
      -
        name: Test image with node version tag with release tag
        if: ${{ env.RELEASE_TAG != 'latest'}}
        run: docker run apify/actor-${{ matrix.image-name }}:${{ matrix.node-version }}-${{ env.RELEASE_TAG }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push images
        run: docker push apify/actor-${{ matrix.image-name }} --all-tags