name: Release playwright images

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag for the images (e.g.: beta)'
        required: true
      apify_version:
        description: 'Apify SDK version (e.g.: ^1.0.0)'
        required: true
      playwright_version:
        description: 'Playwright version (e.g.: 1.7.1)'
        required: true

  repository_dispatch:
    types: [ build-images ]

env:
  RELEASE_TAG: ${{ github.event.inputs.release_tag || github.event.client_payload.release_tag }}
  APIFY_VERSION: ${{ github.event.inputs.apify_version || github.event.client_payload.apify_version }}
  PLAYWRIGHT_VERSION: ${{ github.event.inputs.playwright_version || github.event.client_payload.playwright_version }}
  NODE_LATEST: 16

jobs:
  # Build master images that are not dependent on existing builds.
  build-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: [node-playwright, node-playwright-chrome, node-playwright-firefox, node-playwright-webkit]
        node-version: [14, 15, 16]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Set Dependency Versions
        run: |
          cd ${{ matrix.image-name }}
          node ../.github/scripts/set-dependency-versions.js
      -
        # It seems that it takes at least two minutes before a newly published version
        # becomes available in the NPM registry. We wait before starting the image builds.
        name: Wait For Package Registry
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 2 # timeout for a single attempt
          max_attempts: 3
          retry_wait_seconds: 60 # wait between retries
          command: cd ${{ matrix.image-name }} && npm i --dry-run
      - 
        name: Build image with latest tag
        uses: docker/build-push-action@v2
        if: ${{ env.RELEASE_TAG == 'latest' && matrix.node-version == env.NODE_LATEST }}
        with:
          context: ./${{ matrix.image-name }}
          file: ./${{ matrix.image-name }}/Dockerfile
          build-args: NODE_VERSION=${{ matrix.node-version }}
          load: true
          tags: apify/actor-${{ matrix.image-name }}:${{ env.RELEASE_TAG }}
      - 
        name: Build image with playwright and node versions
        uses: docker/build-push-action@v2
        if: ${{ env.RELEASE_TAG == 'latest' }}
        with:
          context: ./${{ matrix.image-name }}
          file: ./${{ matrix.image-name }}/Dockerfile
          load: true
          build-args: NODE_VERSION=${{ matrix.node-version }}
          tags: apify/actor-${{ matrix.image-name }}:${{ matrix.node-version }}-${{ env.PLAYWRIGHT_VERSION }}
      - 
        name: Build image with release tag
        uses: docker/build-push-action@v2
        if: ${{ env.RELEASE_TAG != 'latest' && matrix.node-version == env.NODE_LATEST }}
        with:
          context: ./${{ matrix.image-name }}
          file: ./${{ matrix.image-name }}/Dockerfile
          build-args: NODE_VERSION=${{ matrix.node-version }}
          load: true
          tags: apify/actor-${{ matrix.image-name }}:${{ env.RELEASE_TAG }}
      -
        name: Test image with release tag
        if: ${{ matrix.node-version == env.NODE_LATEST }}
        run: docker run apify/actor-${{ matrix.image-name }}:${{ env.RELEASE_TAG }}
      -
        name: Test image with node-playwright version tag
        if: ${{ env.RELEASE_TAG == 'latest'}}
        run: docker run apify/actor-${{ matrix.image-name }}:${{ matrix.node-version }}-${{ env.PLAYWRIGHT_VERSION }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push image with release tag
        if: ${{ matrix.node-version == env.NODE_LATEST }}
        run: docker push apify/actor-${{ matrix.image-name }}:${{ env.RELEASE_TAG }}
      -
        name: Push image with playwright version tag
        if: ${{ env.RELEASE_TAG == 'latest' }}
        run: docker push apify/actor-${{ matrix.image-name }}:${{ env.PLAYWRIGHT_VERSION }}